### ISSUE TITLE
Ne pas effacer le script de l'utilisateur en cas d'erreur

### ISSUE THREAD

**Issue by paul-maxime** [Tacticode/tacticode-web#1]
Si l'utilisateur écrit un script ayant un nom de plus de 20 caractères (pourquoi 20 !? pourquoi pas de check front-end !?), le script est reset.

Ceci peut provoquer des morts lentes et douloureuses.

**Comment by arnauddrain** [comment]
Corrigé dans : [#e00957faac44121b4691a09e26595c4549275e83](https://github.com/Tacticode/tacticode-web/commit/e00957faac44121b4691a09e26595c4549275e83)
